// ============================================================
// Reference Sheet Service — implements FR-10:
// "Print-quality topic reference sheets that grow with the student."
//
// Deliberate design choice: this does NOT call the LLM again. It
// aggregates content ALREADY generated by the Lesson Generator
// (lessons.concept_explanation) for every skill the student has
// mastered, grouped by category. This is literally what "grows as
// the student learns" means — the sheet is a compiled view over
// real evidence (mastered skills + their lesson content), not a
// separately-authored document that could drift out of sync.
// ============================================================

import { InMemoryStore } from '../store/InMemoryStore';

export interface ReferenceSheetEntry {
  skillNameAr: string;
  subskill: string;
  principles: string[];
  techniques: string[];
  cautions: string[];
}

export interface ReferenceSheet {
  category: string;
  section: 'verbal' | 'quantitative';
  entries: ReferenceSheetEntry[];
}

export class ReferenceSheetService {
  constructor(private store: InMemoryStore) {}

  /** One sheet per category, but only for categories where the student has mastered at least one skill with lesson content. */
  getSheetsForStudent(studentId: string): ReferenceSheet[] {
    const masteredSkillIds = new Set(
      this.store
        .getActiveLearningRecords(studentId)
        .filter((r) => r.record_type === 'mastery' && r.skill_id)
        .map((r) => r.skill_id as string)
    );
    if (masteredSkillIds.size === 0) return [];

    const byCategory = new Map<string, ReferenceSheet>();

    for (const skillId of masteredSkillIds) {
      const skill = this.store.getSkill(skillId);
      if (!skill) continue;
      const lesson = this.store.lessons.find((l) => l.skill_id === skillId);
      if (!lesson) continue; // no lesson content generated yet for this skill — nothing to compile

      const entry: ReferenceSheetEntry = {
        skillNameAr: skill.name_ar,
        subskill: skill.subskill,
        principles: lesson.concept_explanation.filter((b) => b.kind === 'principle').map((b) => b.text_ar),
        techniques: lesson.concept_explanation.filter((b) => b.kind === 'technique').map((b) => b.text_ar),
        cautions: lesson.concept_explanation.filter((b) => b.kind === 'caution').map((b) => b.text_ar),
      };

      if (!byCategory.has(skill.category)) {
        byCategory.set(skill.category, { category: skill.category, section: skill.section, entries: [] });
      }
      byCategory.get(skill.category)!.entries.push(entry);
    }

    return Array.from(byCategory.values());
  }
}
